# Debian trixie slim arm64

FROM arm64v8/debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    dialog \
    apt-utils \
    ca-certificates \
    curl \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install extra packages
ARG EXTRA_PACKAGES=""
ENV EXTRA_PACKAGES ${EXTRA_PACKAGES}
RUN apt-get update && apt-get install -y --no-install-recommends ${EXTRA_PACKAGES} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
